name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome and thanks for raising this issue!\nWe strive to reply within 48h and will reply as fast as possible."
        pr-message: "Welcome and thank you for contributing! Please make sure you keep Work In Progress as a draft until it is read to be reviewed."
